export const FETCH_ADMIN_ORDERS = 'FETCH_ADMIN_ORDERS'
export const FETCH_ADMIN_ORDER = 'FETCH_ADMIN_ORDER'
export const UPDATE_ADMIN_ORDER = 'UPDATE_ADMIN_ORDER'
export const DELETE_ADMIN_ORDER = 'DELETE_ADMIN_ORDER'
