export const FETCH_ADMIN_PRODUCTS = 'FETCH_ADMIN_PRODUCTS'
export const FETCH_ADMIN_PRODUCT = 'FETCH_ADMIN_PRODUCT'
export const CREATE_ADMIN_PRODUCT = 'CREATE_ADMIN_PRODUCT'
export const UPDATE_ADMIN_PRODUCT = 'UPDATE_ADMIN_PRODUCT'
export const DELETE_ADMIN_PRODUCT = 'DELETE_ADMIN_PRODUCT'

export const TOGGLE_ADMIN_DIALOG = 'TOGGLE_ADMIN_DIALOG'
